Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-12, with the labels that each got.

#211 changing as3/do resource identifiers
  bigip/resource_bigip_as3.go
  bigip/resource_bigip_as3_test.go
  bigip/resource_bigip_do.go
  examples/as3/bigip_as3.tf
  examples/do/bigip_do.tf
Labels: size/XS

#214 Docs update
  website/docs/r/bigip_as3.html.markdown
Labels: documentation, size/XS

#216 updating docs on as3,do resources
  website/docs/r/bigip_as3.html.markdown
  website/docs/r/bigip_do.html.markdown
Labels: documentation, size/XS

#215 docs update from stable-website to master
  website/docs/r/bigip_as3.html.markdown
  website/docs/r/bigip_do.html.markdown
Labels: documentation, size/XS

#217 Adding parameter to specify mgmt port
  bigip/config.go
  bigip/provider.go
  bigip/resource_bigip_ltm_profile_ssl_client.go
  bigip/resource_bigip_ltm_profile_ssl_server.go
  vendor/github.com/f5devcentral/go-bigip/bigip.go
Labels: dependencies, size/S

#219 Fixing sslcert/key replace issue
  bigip/resource_bigip_ssl_certificate.go
  bigip/resource_bigip_ssl_key.go
  examples/servercert2.crt
  examples/serverkey2.key
Labels: size/S

#221 fix for update failures in client ssl profile
  bigip/resource_bigip_ltm_profile_ssl_client.go
  bigip/resource_bigip_ltm_profile_ssl_client_test.go
Labels: size/XS

#222 vendor module update
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL
