Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-11, with the labels that each got.

#179 fix to delete persistence profile for a virtual server
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/XS

#181 Update README.md
  README.md
Labels: size/XS

#183 addind default persistence server feature to virtual server
  bigip/resource_bigip_ltm_virtual_server.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/XS

#184 send datagroup type with the update API content
  bigip/resource_bigip_ltm_datagroup.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/S

#189 Vendor Update for Module changes
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/f5devcentral/go-bigip/.gitignore
  vendor/github.com/f5devcentral/go-bigip/.travis.yml
  vendor/github.com/f5devcentral/go-bigip/LICENSE
  vendor/github.com/f5devcentral/go-bigip/README.md
  vendor/github.com/f5devcentral/go-bigip/app.go
  vendor/github.com/f5devcentral/go-bigip/bigip.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
  vendor/github.com/f5devcentral/go-bigip/shared.go
  vendor/github.com/f5devcentral/go-bigip/sys.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#192 Added Gitlab CI/CD
  .gitlab-ci.yml
Labels: size/XS

#194 Added SSL Certificate/key Import Resource Documentation
  website/bigip.erb
  website/docs/r/bigip_ssl_certificate.html.markdown
  website/docs/r/bigip_ssl_key.html.markdown
Labels: documentation, size/M

#195 Adding DO resource documentation to master
  website/bigip.erb
  website/docs/r/bigip_do.html.markdown
Labels: documentation, size/M

#196 Update resource_bigip_do.go
  bigip/resource_bigip_do.go
Labels: size/XS

#199 Update bigip.erb
  website/bigip.erb
Labels: documentation, size/XS

#197 Update resource_bigip_do.go
  bigip/resource_bigip_do.go
Labels: size/XS

#198 Update bigip.erb
  website/bigip.erb
Labels: documentation, size/XS

#201 Added Client/Server SSL Profile Documentation
  website/bigip.erb
  website/docs/r/bigip_ltm_profile_client_ssl.html.markdown
  website/docs/r/bigip_ltm_profile_server_ssl.html.markdown
Labels: documentation, size/M

#202 Added Client/Server SSL Profile Documentation
  website/bigip.erb
  website/docs/r/bigip_ltm_profile_client_ssl.html.markdown
  website/docs/r/bigip_ltm_profile_server_ssl.html.markdown
Labels: documentation, size/M

#203 Acceptance tests for SSL Certificate/key Import resource
  bigip/resource_bigip_ssl_certificate_test.go
  bigip/resource_bigip_ssl_key_test.go
  examples/servercert.crt
  examples/serverkey.key
Labels: size/L

#191 modifying acceptance tests for virtual server
  bigip/resource_bigip_ltm_virtual_server_test.go
Labels: size/XS

#204 fix for persistence profile issue in virtual server resource
  bigip/resource_bigip_as3.go
  bigip/resource_bigip_do.go
  bigip/resource_bigip_ltm_virtual_server.go
Labels: size/XS

#205 Updating Client/Server SSL Profiles Acceptance tests
  bigip/resource_bigip_ltm_profile_ssl_client.go
  bigip/resource_bigip_ltm_profile_ssl_client_test.go
  bigip/resource_bigip_ltm_profile_ssl_server.go
  bigip/resource_bigip_ltm_profile_ssl_server_test.go
  go.mod
  go.sum
  vendor/github.com/f5devcentral/go-bigip/ltm.go
  vendor/modules.txt
Labels: dependencies, size/XL

#209 added sensitive flag to SSL key/Certificate
  bigip/resource_bigip_ssl_certificate.go
  bigip/resource_bigip_ssl_key.go
Labels: size/XS

#210 Adding docs for pool attachment
  website/docs/r/bigip_ltm_pool_attachment.html.markdown
Labels: documentation, size/XS
