Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-10, with the labels that each got.

#167 Only delete stuff for tenant.
  bigip/resource_bigip_as3.go
Labels: size/XS

#170 updated doc
  website/docs/index.html.markdown
  website/docs/r/bigip_as3.html.markdown
Labels: documentation, size/XS

#172 Adjusted argument name from rules to irules in documentation for virtual server
  website/docs/r/bigip_ltm_virtual_server.html.markdown
Labels: documentation, size/XS

#173 Adjusted argument name from rules to irules in documentation for virtual server
  website/docs/r/bigip_ltm_virtual_server.html.markdown
Labels: documentation, size/XS

#174 Updating ratio for a node (pool-member)
  bigip/resource_bigip_ltm_node.go
  bigip/resource_bigip_ltm_node_test.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/XS

#177 updated changelog
  CHANGELOG.md
Labels: size/XS

#175 Added Support to SSL Certificate/Key Import module
  bigip/provider.go
  bigip/resource_bigip_ssl_certificate.go
  bigip/resource_bigip_ssl_key.go
  examples/bigip_ssl_certificate.tf
  examples/bigip_ssl_key.tf
  vendor/github.com/f5devcentral/go-bigip/bigip.go
  vendor/github.com/f5devcentral/go-bigip/shared.go
  vendor/github.com/f5devcentral/go-bigip/sys.go
Labels: dependencies, size/XL
