Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-04, with the labels that each got.

#74 go module to update vendor for as3 sdk
  examples/as3/README.md
  examples/as3/as3.tf
  examples/as3/as3_http.sh
  examples/as3/example1.json
  examples/as3/example2.json
  examples/as3/install_as3.sh
  go.mod
  go.sum
  vendor/github.com/f5devcentral/go-bigip/app.go
  vendor/modules.txt
Labels: dependencies, size/XL

#84 implement pool attachment import
  CHANGELOG.md
  bigip/resource_bigip_ltm_pool_attachment.go
Labels: size/S

#87 fixed #80, #81
  bigip/resource_bigip_ltm_profile_tcp.go
Labels: size/XS

#90 updated Change log
  CHANGELOG.md
Labels: size/XS

#91 updated vendor using module
  go.mod
  go.sum
  vendor/github.com/f5devcentral/go-bigip/.gitignore
  vendor/github.com/f5devcentral/go-bigip/app.go
  vendor/github.com/f5devcentral/go-bigip/net.go
  vendor/github.com/f5devcentral/go-bigip/partitions.go
  vendor/modules.txt
Labels: dependencies, size/M

#93 changed default to computed
  bigip/resource_bigip_ltm_node.go
Labels: size/XS

#94 removed default
  bigip/resource_bigip_ltm_monitor.go
  bigip/resource_bigip_ltm_pool.go
  examples/master.tf
Labels: size/S

#96 Monitor: add "Computed: true" to additional optional attributes
  bigip/resource_bigip_ltm_monitor.go
Labels: size/XS

#97 vendor update
  go.mod
  go.sum
  vendor/github.com/f5devcentral/go-bigip/device.go
  vendor/github.com/f5devcentral/go-bigip/net.go
  vendor/modules.txt
Labels: dependencies, size/L
