Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-09, with the labels that each got.

#154 added as3 documentation
  website/bigip.erb
  website/docs/r/bigip_as3.html.markdown
Labels: documentation, size/S

#155 added as3 documentation
  website/docs/r/bigip_as3.html.markdown
Labels: documentation, size/XS

#153 Fixed Virtual server state enabled/disabled issue
  bigip/resource_bigip_ltm_virtual_server.go
  bigip/resource_bigip_ltm_virtual_server_test.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/L

#78 Update bigip_sys_dns resource documentation and sidebar link
  website/bigip.erb
  website/docs/r/bigip_sys_dns.html.markdown
Labels: documentation, size/XS

#156 Stable website
  website/bigip.erb
  website/docs/r/bigip_sys_dns.html.markdown
Labels: documentation, size/XS
