Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-08, with the labels that each got.

#137 Bigip AS3 integration with Terraform
  bigip/provider.go
  bigip/resource_bigip_as3.go
  bigip/resource_bigip_as3_test.go
  examples/as3/bigip_as3.tf
Labels: size/L

#134 Ssl Client Profile and Server Profile feature pull request ready
  bigip/provider.go
  bigip/resource_bigip_ltm_profile_ssl_client.go
  bigip/resource_bigip_ltm_profile_ssl_client_test.go
  bigip/resource_bigip_ltm_profile_ssl_server.go
  bigip/resource_bigip_ltm_profile_ssl_server_test.go
Labels: size/XXL

#117 fix missing brace
  examples/bigip_net_vlan.tf
Labels: size/XS

#139 changing required parameters to optional in _bigip_ltm_policy
  bigip/resource_bigip_ltm_policy.go
Labels: size/XS

#130 pass examples through terraform fmt
  website/docs/r/bigip_cm_devicegroup.html.markdown
  website/docs/r/bigip_ltm_irule.html.markdown
  website/docs/r/bigip_ltm_monitor.html.markdown
  website/docs/r/bigip_ltm_node.html.markdown
  website/docs/r/bigip_ltm_persistence_profile_cookie.html.markdown
  website/docs/r/bigip_ltm_persistence_profile_ssl.html.markdown
  website/docs/r/bigip_ltm_policy.html.markdown
  website/docs/r/bigip_ltm_pool.html.markdown
  website/docs/r/bigip_ltm_profile_http.html.markdown
  website/docs/r/bigip_sys_provision.html.markdown
Labels: documentation, size/L

#143 updated change log
  CHANGELOG.md
Labels: size/XS

#141 fix policy uploading to defined partition
  bigip/provider.go
  bigip/resource_bigip_ltm_policy.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/M

#144 vendor update
  go.mod
  go.sum
  vendor/github.com/f5devcentral/go-bigip/ltm.go
  vendor/modules.txt
Labels: dependencies, size/XS

#145 Revert "fix policy uploading to defined partition"
  bigip/provider.go
  bigip/resource_bigip_ltm_policy.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/M

#146 updated Change log
  CHANGELOG.md
Labels: size/XS

#149 fix for #148
  bigip/resource_bigip_ltm_node.go
  bigip/resource_bigip_ltm_node_test.go
Labels: size/XS

#151 Fixed pool/virtual-server resource default description issue
  bigip/resource_bigip_ltm_node.go
  bigip/resource_bigip_ltm_pool.go
  bigip/resource_bigip_ltm_virtual_server.go
  bigip/resource_bigip_ltm_virtual_server_test.go
Labels: size/XS
