Repository F5Networks/terraform-provider-bigip, pull requests merged in 2019-01, with the labels that each got.

#32 updated travis file
  .travis.yml
  bigip/resource_bigip_ltm_virtual_server.go
  bigip/resource_bigip_sys_snmp_traps.go
Labels: size/XS

#37 updated Changelog
  CHANGELOG.md
Labels: size/XS

#38 documentation for httpcompress profile added
  website/docs/r/bigip_ltm_profile_httpcompress.html.markdown
Labels: documentation, size/XS

#39 indent document
  website/docs/r/bigip_ltm_profile_httpcompress.html.markdown
Labels: documentation, size/XS

#40 added vlan list issue #35
  Gopkg.lock
  bigip/resource_bigip_ltm_snat.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/f5devcentral/go-bigip/ltm.go
Labels: dependencies, size/XS

#41 ~website: Alphabetize sidebar links.
  website/bigip.erb
Labels: documentation, size/M

#42 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS

#50 updated node doc
  website/docs/r/bigip_ltm_node.html.markdown
Labels: documentation, size/XS

#51 added dafult values as required to resource tcp profile
  bigip/resource_bigip_ltm_profile_fastl4.go
  bigip/resource_bigip_ltm_profile_http2.go
  bigip/resource_bigip_ltm_profile_tcp.go
Labels: size/XS

#52 added default values to one-Connect
  bigip/resource_bigip_ltm_profile_oneconnect.go
Labels: size/XS
