Repository F5Networks/terraform-provider-bigip, pull requests merged in 2020-07, with the labels that each got.

#310 Adding documentation for BIG-IQ As3 resource
  website/docs/r/bigiq_as3.html.markdown
Labels: documentation, size/M

#311 Adding documentation for BIG-IQ As3 resource
  website/docs/r/bigiq_as3.html.markdown
Labels: documentation, size/M

#312 updated documentation to disable teem
  website/docs/index.html.markdown
Labels: documentation, size/XS

#315 cross check for bigiq as3 documentation
  website/bigip.erb
  website/docs/r/bigip_bigiq_as3.html.markdown
Labels: documentation, size/XS

#316 Update README.md
  README.md
Labels: size/XS
